### ISSUE TITLE
NotReallyAnIssue: Request: Viewbox control

### ISSUE THREAD

**Issue by SuperJMN** [PanAndZoom/PanAndZoom#2]
A pure layout control that is useful for some scenarios and I have already missed in Avalonia :)

**Comment by wieslawsoltes** [comment]
@SuperJMN That would be nice, but the goal of `PanAndZoom` was only to be pan and zoom control using `RenderTransform`. You can emulate the behavior of ViewBox by setting the AutoFitMode property to Extent or Fill.

https://github.com/PanAndZoom/PanAndZoom/blob/master/src/Avalonia.Controls.PanAndZoom/ZoomBorder.cs#L45
https://github.com/PanAndZoom/PanAndZoom/blob/master/src/Avalonia.Controls.PanAndZoom/AutoFitMode.cs
